import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"
import WalletProviderWrapper from "./Components/WalletProvider";
import { CartLengthProvider } from "./Components/HomePage/Products";
import { SellerPubkeyProvider } from "./cart/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletProviderWrapper>
          <CartLengthProvider>
            <SellerPubkeyProvider>
              {children}
              <Toaster 
                position="top-right"
                toastOptions={{
                  duration:3000,
                  style:{
                    background:'#1e293b',
                    color:"#fff"
                  }
                }}
              />
            </SellerPubkeyProvider>
          </CartLengthProvider>
        </WalletProviderWrapper>
      </body>
    </html>
  );
}
